name: Build & Staging
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  ADD_DEFAULT_LANGUAGES: 1
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
          K8S_SECRET_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://tunnistamo.${{ env.BASE_DOMAIN }}/openid"
          K8S_SECRET_ILMOITIN_QUEUE_NOTIFICATIONS: 1
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.SECRET_MAILGUN_API_KEY }}
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
          K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
          K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
          K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.ninja"
          K8S_SECRET_DEFAULT_FILE_STORAGE: "storages.backends.gcloud.GoogleCloudStorage"
          K8S_FILE_SECRET_STAGING_GCS_BUCKET_CREDENTIALS: ${{ secrets.STAGING_GCS_BUCKET_CREDENTIALS }}
          K8S_SECRET_GS_BUCKET_NAME: ${{ secrets.STAGING_GCS_BUCKET_NAME }}
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          K8S_SECRET_SENTRY_ENVIRONMENT: "test"
          K8S_SECRET_ENABLE_GRAPHIQL: 1
          K8S_SECRET_KUKKUU_UI_BASE_URL: "https://kukkuu-ui.${{ env.BASE_DOMAIN }}"
          K8S_SECRET_ADD_DEFAULT_LANGUAGES: 1
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STAGING }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STAGING }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STAGING }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STAGING }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STAGING }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STAGING }}
          K8S_SECRET_KUKKUU_NOTIFICATIONS_SHEET_ID: ${{ secrets.K8S_SECRET_KUKKUU_NOTIFICATIONS_SHEET_ID_STAGING }}

      - name: Deploy send mail cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: send-mail-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STAGING }}
          schedule: "* * * * *" # every min
          secret_name: "project-staging-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py send_mail}"
          max_duration: 900 # 15min

      - name: Deploy retry deferred mails cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: retry-deferred-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STAGING }}
          schedule: "*/20 * * * *" # every 20 mins
          secret_name: "project-staging-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py retry_deferred}"
          max_duration: 900 # 15min

      - name: Deploy send reminder notifications cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: send-reminder-notifications-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STAGING }}
          schedule: "0 12 * * *" # daily at noon UTC
          secret_name: "project-staging-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py send_reminder_notifications}"
